export interface Coin {
  denomination: string;
  year: number;
  type: string;
  issue: string;
  mint: string;
  mintmark?: string;
  mintage?: number;
  designer: string;
}

export default defineEventHandler((event) => {
  return [
    {
      denomination: "cent",
      year: 1793,
      type: "Flowing Hair",
      issue: "1793 Chain",
      mint: "Philadelphia",
      mintage: 36103,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1793,
      type: "Flowing Hair",
      issue: "1793 Wreath",
      mint: "Philadelphia",
      mintage: 63353,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1793,
      type: "Liberty Cap",
      issue: "1793",
      mint: "Philadelphia",
      mintage: 11056,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1794,
      type: "Liberty Cap",
      issue: "1794",
      mint: "Philadelphia",
      mintage: 918521,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1795,
      type: "Liberty Cap",
      issue: "1795 Lettered Edge",
      mint: "Philadelphia",
      mintage: 37000,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1795,
      type: "Liberty Cap",
      issue: "1795 Plain Edge",
      mint: "Philadelphia",
      mintage: 501500,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1796,
      type: "Liberty Cap",
      issue: "1796",
      mint: "Philadelphia",
      mintage: 109825,
      designer: "Henry Voight",
    },
    {
      denomination: "cent",
      year: 1796,
      type: "Draped Bust",
      issue: "1796",
      mint: "Philadelphia",
      mintage: 363375,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1797,
      type: "Draped Bust",
      issue: "1797",
      mint: "Philadelphia",
      mintage: 897510,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1798,
      type: "Draped Bust",
      issue: "1798",
      mint: "Philadelphia",
      mintage: 1841745,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1799,
      type: "Draped Bust",
      issue: "1799",
      mint: "Philadelphia",
      mintage: 904585,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1800,
      type: "Draped Bust",
      issue: "1800",
      mint: "Philadelphia",
      mintage: 2822175,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1801,
      type: "Draped Bust",
      issue: "1801",
      mint: "Philadelphia",
      mintage: 1362837,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1802,
      type: "Draped Bust",
      issue: "1802",
      mint: "Philadelphia",
      mintage: 3435100,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1803,
      type: "Draped Bust",
      issue: "1803",
      mint: "Philadelphia",
      mintage: 3131691,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1804,
      type: "Draped Bust",
      issue: "1804",
      mint: "Philadelphia",
      mintage: 96500,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1804,
      type: "Draped Bust",
      issue: "1804 Restrike",
      mint: "Philadelphia",
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1805,
      type: "Draped Bust",
      issue: "1805",
      mint: "Philadelphia",
      mintage: 941116,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1806,
      type: "Draped Bust",
      issue: "1806",
      mint: "Philadelphia",
      mintage: 348000,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1807,
      type: "Draped Bust",
      issue: "1807",
      mint: "Philadelphia",
      mintage: 829221,
      designer: "Robert Scot",
    },
    {
      denomination: "cent",
      year: 1808,
      type: "Classic Head",
      issue: "1808",
      mint: "Philadelphia",
      mintage: 1007000,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1809,
      type: "Classic Head",
      issue: "1809",
      mint: "Philadelphia",
      mintage: 222867,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1810,
      type: "Classic Head",
      issue: "1810",
      mint: "Philadelphia",
      mintage: 1458500,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1811,
      type: "Classic Head",
      issue: "1811",
      mint: "Philadelphia",
      mintage: 218025,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1812,
      type: "Classic Head",
      issue: "1812",
      mint: "Philadelphia",
      mintage: 1075500,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1813,
      type: "Classic Head",
      issue: "1813",
      mint: "Philadelphia",
      mintage: 418000,
      designer: "John Reich",
    },
    {
      denomination: "cent",
      year: 1814,
      type: "Classic Head",
      issue: "1814",
      mint: "Philadelphia",
      mintage: 357830,
      designer: "John Reich",
    },
  ] as Coin[];
});
